# Lets run on the new infrastructure
sudo: false
language: python
python:
  - "3.5"
  - "2.7"

env:
  - DB=sqlite
  - DB=postgres

before_script:
  # Make a posgres database
  - if [[ $DB == postgres ]]; then psql -c 'create database aristotle_test_db;' -U postgres; fi

install:
  - pip install coveralls
  - pip install tox

script:
  - tox --skip-missing-interpreters

after_success:
  - coveralls
